-- =====================================================================
-- Seed: Türkiye'ye özel EK haber kaynakları (il + ilçe + konu/aktör).
-- OTOMATİK ÜRETİLDİ — elle düzenlemeyin. Kaynak: sources.data.ts buildTurkeyExtra
-- Idempotent: ON CONFLICT (feed_url) DO NOTHING.  Toplam: 407
-- =====================================================================

INSERT INTO sources (name, homepage, feed_url, kind, orientation, lang, country_iso2) VALUES
  ('Google Haberler — Adana (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Adana%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Adıyaman (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ad%C4%B1yaman%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Afyonkarahisar (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Afyonkarahisar%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ağrı (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22A%C4%9Fr%C4%B1%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Amasya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Amasya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ankara (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ankara%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Antalya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Antalya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Artvin (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Artvin%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Aydın (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ayd%C4%B1n%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Balıkesir (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bal%C4%B1kesir%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bilecik (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bilecik%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bingöl (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bing%C3%B6l%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bitlis (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bitlis%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bolu (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bolu%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Burdur (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Burdur%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bursa (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bursa%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çanakkale (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87anakkale%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çankırı (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87ank%C4%B1r%C4%B1%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çorum (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87orum%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Denizli (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Denizli%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Diyarbakır (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Diyarbak%C4%B1r%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Edirne (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Edirne%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Elazığ (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Elaz%C4%B1%C4%9F%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Erzincan (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Erzincan%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Erzurum (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Erzurum%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Eskişehir (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Eski%C5%9Fehir%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gaziantep (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Gaziantep%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Giresun (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Giresun%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gümüşhane (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22G%C3%BCm%C3%BC%C5%9Fhane%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Hakkari (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Hakkari%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Hatay (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Hatay%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Isparta (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Isparta%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Mersin (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mersin%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İstanbul (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0stanbul%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İzmir (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0zmir%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kars (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kars%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kastamonu (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kastamonu%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kayseri (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kayseri%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kırklareli (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C4%B1rklareli%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kırşehir (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C4%B1r%C5%9Fehir%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kocaeli (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kocaeli%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Konya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Konya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kütahya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C3%BCtahya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Malatya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Malatya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Manisa (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Manisa%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kahramanmaraş (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kahramanmara%C5%9F%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Mardin (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mardin%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Muğla (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mu%C4%9Fla%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Muş (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mu%C5%9F%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Nevşehir (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Nev%C5%9Fehir%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Niğde (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ni%C4%9Fde%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ordu (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ordu%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Rize (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Rize%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sakarya (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sakarya%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Samsun (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Samsun%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Siirt (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Siirt%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sinop (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sinop%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sivas (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sivas%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tekirdağ (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tekirda%C4%9F%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tokat (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tokat%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Trabzon (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Trabzon%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tunceli (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tunceli%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şanlıurfa (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Eanl%C4%B1urfa%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Uşak (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22U%C5%9Fak%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Van (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Van%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Yozgat (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Yozgat%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Zonguldak (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Zonguldak%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Aksaray (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Aksaray%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bayburt (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bayburt%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Karaman (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Karaman%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kırıkkale (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C4%B1r%C4%B1kkale%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Batman (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Batman%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şırnak (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9E%C4%B1rnak%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bartın (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bart%C4%B1n%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ardahan (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ardahan%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Iğdır (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22I%C4%9Fd%C4%B1r%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Yalova (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Yalova%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Karabük (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Karab%C3%BCk%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kilis (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kilis%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Osmaniye (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Osmaniye%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Düzce (il)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22D%C3%BCzce%22%20haberleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kadıköy (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kad%C4%B1k%C3%B6y%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Beşiktaş (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Be%C5%9Fikta%C5%9F%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Üsküdar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%9Csk%C3%BCdar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şişli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Ei%C5%9Fli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Beyoğlu (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Beyo%C4%9Flu%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Fatih (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Fatih%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bakırköy (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bak%C4%B1rk%C3%B6y%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Maltepe (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Maltepe%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kartal (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kartal%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Pendik (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Pendik%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ümraniye (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%9Cmraniye%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ataşehir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ata%C5%9Fehir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sarıyer (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sar%C4%B1yer%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Beylikdüzü (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Beylikd%C3%BCz%C3%BC%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Esenyurt (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Esenyurt%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Başakşehir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ba%C5%9Fak%C5%9Fehir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bağcılar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ba%C4%9Fc%C4%B1lar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Küçükçekmece (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C3%BC%C3%A7%C3%BCk%C3%A7ekmece%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Büyükçekmece (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22B%C3%BCy%C3%BCk%C3%A7ekmece%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tuzla (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tuzla%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sancaktepe (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sancaktepe%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çekmeköy (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87ekmek%C3%B6y%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Eyüpsultan (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ey%C3%BCpsultan%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gaziosmanpaşa (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Gaziosmanpa%C5%9Fa%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Zeytinburnu (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Zeytinburnu%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çankaya (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87ankaya%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Keçiören (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ke%C3%A7i%C3%B6ren%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Yenimahalle (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Yenimahalle%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Mamak (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mamak%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Etimesgut (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Etimesgut%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sincan (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sincan%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Altındağ (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Alt%C4%B1nda%C4%9F%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Pursaklar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Pursaklar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gölbaşı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22G%C3%B6lba%C5%9F%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Polatlı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Polatl%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Konak (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Konak%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Karşıyaka (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kar%C5%9F%C4%B1yaka%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bornova (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bornova%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Buca (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Buca%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bayraklı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bayrakl%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çiğli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87i%C4%9Fli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gaziemir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Gaziemir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Karabağlar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Karaba%C4%9Flar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çeşme (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87e%C5%9Fme%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Menemen (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Menemen%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Nilüfer (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Nil%C3%BCfer%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Osmangazi (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Osmangazi%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Yıldırım (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Y%C4%B1ld%C4%B1r%C4%B1m%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Muratpaşa (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Muratpa%C5%9Fa%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kepez (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kepez%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Konyaaltı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Konyaalt%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Seyhan (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Seyhan%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çukurova (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87ukurova%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Selçuklu (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sel%C3%A7uklu%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Meram (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Meram%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şahinbey (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Eahinbey%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şehitkamil (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Eehitkamil%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İlkadım (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0lkad%C4%B1m%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Atakum (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Atakum%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ortahisar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ortahisar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Battalgazi (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Battalgazi%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Odunpazarı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Odunpazar%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tepebaşı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tepeba%C5%9F%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Avcılar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Avc%C4%B1lar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bahçelievler (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bah%C3%A7elievler%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bayrampaşa (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bayrampa%C5%9Fa%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Esenler (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Esenler%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Güngören (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22G%C3%BCng%C3%B6ren%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kâğıthane (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C3%A2%C4%9F%C4%B1thane%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sultangazi (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sultangazi%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sultanbeyli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sultanbeyli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Arnavutköy (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Arnavutk%C3%B6y%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çatalca (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87atalca%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Silivri (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Silivri%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şile (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Eile%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Adalar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Adalar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Beykoz (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Beykoz%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bahçeşehir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bah%C3%A7e%C5%9Fehir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çubuk (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87ubuk%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kahramankazan (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kahramankazan%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Elmadağ (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Elmada%C4%9F%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Beypazarı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Beypazar%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Haymana (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Haymana%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Şereflikoçhisar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C5%9Eerefliko%C3%A7hisar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Torbalı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Torbal%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ödemiş (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%96demi%C5%9F%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tire (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tire%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bergama (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bergama%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Aliağa (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Alia%C4%9Fa%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Urla (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Urla%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Foça (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Fo%C3%A7a%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Dikili (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Dikili%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İnegöl (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0neg%C3%B6l%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gemlik (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Gemlik%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Mudanya (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Mudanya%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Alanya (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Alanya%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Manavgat (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Manavgat%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Serik (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Serik%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kemer (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Kemer%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Tarsus (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Tarsus%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ceyhan (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ceyhan%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İskenderun (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0skenderun%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ereğli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ere%C4%9Fli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Akşehir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ak%C5%9Fehir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Nazilli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Nazilli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Söke (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22S%C3%B6ke%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bodrum (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bodrum%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Fethiye (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Fethiye%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Marmaris (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Marmaris%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Milas (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Milas%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çorlu (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87orlu%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Çerkezköy (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%87erkezk%C3%B6y%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Gebze (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Gebze%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Darıca (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Dar%C4%B1ca%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Körfez (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C3%B6rfez%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — İzmit (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C4%B0zmit%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Adapazarı (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Adapazar%C4%B1%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bandırma (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Band%C4%B1rma%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Edremit (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Edremit%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Turgutlu (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Turgutlu%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Salihli (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Salihli%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Akhisar (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Akhisar%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Soma (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Soma%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Carşamba (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Car%C5%9Famba%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bafra (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bafra%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ünye (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22%C3%9Cnye%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Fatsa (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Fatsa%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Sorgun (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Sorgun%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Develi (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Develi%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bor (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bor%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Viranşehir (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Viran%C5%9Fehir%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Siverek (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Siverek%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Nusaybin (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Nusaybin%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Cizre (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Cizre%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Silopi (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Silopi%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Kızıltepe (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22K%C4%B1z%C4%B1ltepe%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Ergani (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Ergani%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — Bismil (ilçe)', 'https://news.google.com', 'https://news.google.com/rss/search?q=%22Bismil%22&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Dolar/TL', 'https://news.google.com', 'https://news.google.com/rss/search?q=dolar%20kuru&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Euro/TL', 'https://news.google.com', 'https://news.google.com/rss/search?q=euro%20kuru&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Altın', 'https://news.google.com', 'https://news.google.com/rss/search?q=gram%20alt%C4%B1n&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Borsa İstanbul', 'https://news.google.com', 'https://news.google.com/rss/search?q=Borsa%20%C4%B0stanbul%20BIST&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Faiz', 'https://news.google.com', 'https://news.google.com/rss/search?q=Merkez%20Bankas%C4%B1%20faiz&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Enflasyon', 'https://news.google.com', 'https://news.google.com/rss/search?q=enflasyon%20T%C3%9C%C4%B0K&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Asgari ücret', 'https://news.google.com', 'https://news.google.com/rss/search?q=asgari%20%C3%BCcret&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Emeklilik', 'https://news.google.com', 'https://news.google.com/rss/search?q=emeklilik%20EYT&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Zam', 'https://news.google.com', 'https://news.google.com/rss/search?q=zam%20memur%20emekli&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Konut', 'https://news.google.com', 'https://news.google.com/rss/search?q=konut%20fiyatlar%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Kira', 'https://news.google.com', 'https://news.google.com/rss/search?q=kira%20art%C4%B1%C5%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Akaryakıt', 'https://news.google.com', 'https://news.google.com/rss/search?q=benzin%20mazot%20zamm%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Vergi', 'https://news.google.com', 'https://news.google.com/rss/search?q=vergi%20d%C3%BCzenlemesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Bütçe', 'https://news.google.com', 'https://news.google.com/rss/search?q=merkezi%20b%C3%BCt%C3%A7e&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İhracat', 'https://news.google.com', 'https://news.google.com/rss/search?q=ihracat%20rakamlar%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Cari açık', 'https://news.google.com', 'https://news.google.com/rss/search?q=cari%20a%C3%A7%C4%B1k&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İşsizlik', 'https://news.google.com', 'https://news.google.com/rss/search?q=i%C5%9Fsizlik%20oran%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Kredi', 'https://news.google.com', 'https://news.google.com/rss/search?q=kredi%20faizi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Doğalgaz', 'https://news.google.com', 'https://news.google.com/rss/search?q=do%C4%9Falgaz%20fiyat%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Elektrik', 'https://news.google.com', 'https://news.google.com/rss/search?q=elektrik%20zamm%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · TBMM', 'https://news.google.com', 'https://news.google.com/rss/search?q=TBMM%20Meclis&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Cumhurbaşkanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Cumhurba%C5%9Fkan%C4%B1%20Erdo%C4%9Fan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Kabine', 'https://news.google.com', 'https://news.google.com/rss/search?q=Cumhurba%C5%9Fkanl%C4%B1%C4%9F%C4%B1%20kabine&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · CHP', 'https://news.google.com', 'https://news.google.com/rss/search?q=CHP&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · AK Parti', 'https://news.google.com', 'https://news.google.com/rss/search?q=AK%20Parti&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · MHP', 'https://news.google.com', 'https://news.google.com/rss/search?q=MHP&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İYİ Parti', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0Y%C4%B0%20Parti&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · DEM Parti', 'https://news.google.com', 'https://news.google.com/rss/search?q=DEM%20Parti&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Saadet', 'https://news.google.com', 'https://news.google.com/rss/search?q=Saadet%20Partisi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yeniden Refah', 'https://news.google.com', 'https://news.google.com/rss/search?q=Yeniden%20Refah%20Partisi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Anayasa', 'https://news.google.com', 'https://news.google.com/rss/search?q=yeni%20anayasa&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Seçim', 'https://news.google.com', 'https://news.google.com/rss/search?q=se%C3%A7im&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yerel seçim', 'https://news.google.com', 'https://news.google.com/rss/search?q=yerel%20se%C3%A7im%20belediye&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Dokunulmazlık', 'https://news.google.com', 'https://news.google.com/rss/search?q=milletvekili%20dokunulmazl%C4%B1k&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İBB', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0stanbul%20B%C3%BCy%C3%BCk%C5%9Fehir%20Belediyesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ankara Büyükşehir', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ankara%20B%C3%BCy%C3%BCk%C5%9Fehir%20Belediyesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Muhalefet', 'https://news.google.com', 'https://news.google.com/rss/search?q=muhalefet&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Dış politika', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20d%C4%B1%C5%9F%20politika&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · NATO', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20NATO&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Avrupa Birliği', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20AB%20ili%C5%9Fkileri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · ABD ilişkileri', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20ABD%20ili%C5%9Fkileri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Rusya', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Rusya&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yunanistan', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Yunanistan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Suriye', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Suriye&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Irak', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Irak&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İran', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20%C4%B0ran&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · KKTC', 'https://news.google.com', 'https://news.google.com/rss/search?q=KKTC%20K%C4%B1br%C4%B1s&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Azerbaycan', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Azerbaycan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İsrail', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20%C4%B0srail&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Filistin', 'https://news.google.com', 'https://news.google.com/rss/search?q=Filistin%20Gazze&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Mısır', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20M%C4%B1s%C4%B1r&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Libya', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Libya&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ukrayna', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Ukrayna%20sava%C5%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · TSK', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrk%20Silahl%C4%B1%20Kuvvetleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Savunma sanayii', 'https://news.google.com', 'https://news.google.com/rss/search?q=savunma%20sanayii&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · SİHA', 'https://news.google.com', 'https://news.google.com/rss/search?q=Bayraktar%20S%C4%B0HA%20%C4%B0HA&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Terörle mücadele', 'https://news.google.com', 'https://news.google.com/rss/search?q=ter%C3%B6rle%20m%C3%BCcadele%20operasyon&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sınır güvenliği', 'https://news.google.com', 'https://news.google.com/rss/search?q=s%C4%B1n%C4%B1r%20g%C3%BCvenli%C4%9Fi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · MİT', 'https://news.google.com', 'https://news.google.com/rss/search?q=M%C4%B0T%20istihbarat&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Aselsan', 'https://news.google.com', 'https://news.google.com/rss/search?q=Aselsan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Baykar', 'https://news.google.com', 'https://news.google.com/rss/search?q=Baykar&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · TUSAŞ', 'https://news.google.com', 'https://news.google.com/rss/search?q=TUSA%C5%9E%20TAI&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · KAAN', 'https://news.google.com', 'https://news.google.com/rss/search?q=milli%20muharip%20u%C3%A7ak%20KAAN&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Enerji', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20enerji&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Petrol', 'https://news.google.com', 'https://news.google.com/rss/search?q=petrol%20arama&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Maden', 'https://news.google.com', 'https://news.google.com/rss/search?q=madencilik&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tarım', 'https://news.google.com', 'https://news.google.com/rss/search?q=tar%C4%B1m%20%C3%A7ift%C3%A7i&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Gıda', 'https://news.google.com', 'https://news.google.com/rss/search?q=g%C4%B1da%20fiyatlar%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Otomotiv', 'https://news.google.com', 'https://news.google.com/rss/search?q=otomotiv%20sekt%C3%B6r%C3%BC&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · TOGG', 'https://news.google.com', 'https://news.google.com/rss/search?q=TOGG&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Turizm', 'https://news.google.com', 'https://news.google.com/rss/search?q=turizm%20sezonu&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sanayi', 'https://news.google.com', 'https://news.google.com/rss/search?q=sanayi%20%C3%BCretimi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İnşaat', 'https://news.google.com', 'https://news.google.com/rss/search?q=in%C5%9Faat%20sekt%C3%B6r%C3%BC&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Havacılık', 'https://news.google.com', 'https://news.google.com/rss/search?q=THY%20havayolu&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Lojistik', 'https://news.google.com', 'https://news.google.com/rss/search?q=lojistik&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Bankacılık', 'https://news.google.com', 'https://news.google.com/rss/search?q=bankac%C4%B1l%C4%B1k%20sekt%C3%B6r%C3%BC&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sigorta', 'https://news.google.com', 'https://news.google.com/rss/search?q=sigorta%20sekt%C3%B6r%C3%BC&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Deprem', 'https://news.google.com', 'https://news.google.com/rss/search?q=deprem&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · AFAD', 'https://news.google.com', 'https://news.google.com/rss/search?q=AFAD&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sağlık', 'https://news.google.com', 'https://news.google.com/rss/search?q=sa%C4%9Fl%C4%B1k%20Bakanl%C4%B1%C4%9F%C4%B1%20hastane&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Eğitim', 'https://news.google.com', 'https://news.google.com/rss/search?q=MEB%20e%C4%9Fitim&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Üniversite', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C3%BCniversite%20Y%C3%96K&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yargı', 'https://news.google.com', 'https://news.google.com/rss/search?q=yarg%C4%B1%20mahkeme&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Adalet', 'https://news.google.com', 'https://news.google.com/rss/search?q=Adalet%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İçişleri', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0%C3%A7i%C5%9Fleri%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Göç', 'https://news.google.com', 'https://news.google.com/rss/search?q=g%C3%B6%C3%A7men%20s%C4%B1%C4%9F%C4%B1nmac%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İklim', 'https://news.google.com', 'https://news.google.com/rss/search?q=iklim%20de%C4%9Fi%C5%9Fikli%C4%9Fi%20kurakl%C4%B1k&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Orman yangını', 'https://news.google.com', 'https://news.google.com/rss/search?q=orman%20yang%C4%B1n%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Trafik', 'https://news.google.com', 'https://news.google.com/rss/search?q=trafik%20kazas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Grev', 'https://news.google.com', 'https://news.google.com/rss/search?q=grev%20i%C5%9F%C3%A7i&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sendika', 'https://news.google.com', 'https://news.google.com/rss/search?q=sendika&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Kadın hakları', 'https://news.google.com', 'https://news.google.com/rss/search?q=kad%C4%B1n%20cinayetleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yapay zeka', 'https://news.google.com', 'https://news.google.com/rss/search?q=yapay%20zeka%20T%C3%BCrkiye&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Teknoloji', 'https://news.google.com', 'https://news.google.com/rss/search?q=teknoloji&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Uzay', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20uzay%20ajans%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · TÜBİTAK', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%9CB%C4%B0TAK&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Siber güvenlik', 'https://news.google.com', 'https://news.google.com/rss/search?q=siber%20g%C3%BCvenlik&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Startup', 'https://news.google.com', 'https://news.google.com/rss/search?q=giri%C5%9Fim%20startup&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Telekomünikasyon', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrk%20Telekom%20Turkcell&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · THY', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrk%20Hava%20Yollar%C4%B1%20THY&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Türk Telekom', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrk%20Telekom&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Turkcell', 'https://news.google.com', 'https://news.google.com/rss/search?q=Turkcell&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tüpraş', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCpra%C5%9F&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ereğli Demir Çelik', 'https://news.google.com', 'https://news.google.com/rss/search?q=Erdemir&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Koç Holding', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ko%C3%A7%20Holding&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sabancı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Sabanc%C4%B1%20Holding&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Garanti BBVA', 'https://news.google.com', 'https://news.google.com/rss/search?q=Garanti%20BBVA&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İş Bankası', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0%C5%9F%20Bankas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Akbank', 'https://news.google.com', 'https://news.google.com/rss/search?q=Akbank&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ziraat Bankası', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ziraat%20Bankas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ford Otosan', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ford%20Otosan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tofaş', 'https://news.google.com', 'https://news.google.com/rss/search?q=Tofa%C5%9F&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Arçelik', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ar%C3%A7elik&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · BİM', 'https://news.google.com', 'https://news.google.com/rss/search?q=B%C4%B0M&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Şok Marketler', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C5%9Eok%20Marketler&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Migros', 'https://news.google.com', 'https://news.google.com/rss/search?q=Migros&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Petkim', 'https://news.google.com', 'https://news.google.com/rss/search?q=Petkim&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Şişecam', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C5%9Ei%C5%9Fecam&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Turkish Airlines kargo', 'https://news.google.com', 'https://news.google.com/rss/search?q=Turkish%20Cargo&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · ASELSAN ihracat', 'https://news.google.com', 'https://news.google.com/rss/search?q=Aselsan%20ihracat%20s%C3%B6zle%C5%9Fme&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Roketsan', 'https://news.google.com', 'https://news.google.com/rss/search?q=Roketsan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Havelsan', 'https://news.google.com', 'https://news.google.com/rss/search?q=Havelsan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · EYAS', 'https://news.google.com', 'https://news.google.com/rss/search?q=Eczac%C4%B1ba%C5%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Vakıfbank', 'https://news.google.com', 'https://news.google.com/rss/search?q=Vak%C4%B1fbank&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Hazine Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Hazine%20ve%20Maliye%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sanayi Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Sanayi%20ve%20Teknoloji%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Enerji Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Enerji%20ve%20Tabii%20Kaynaklar%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Dışişleri Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=D%C4%B1%C5%9Fi%C5%9Fleri%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Milli Savunma Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Milli%20Savunma%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tarım Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Tar%C4%B1m%20ve%20Orman%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ticaret Bakanlığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ticaret%20Bakanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · SPK', 'https://news.google.com', 'https://news.google.com/rss/search?q=Sermaye%20Piyasas%C4%B1%20Kurulu%20SPK&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · BDDK', 'https://news.google.com', 'https://news.google.com/rss/search?q=BDDK&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Rekabet Kurumu', 'https://news.google.com', 'https://news.google.com/rss/search?q=Rekabet%20Kurumu&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · RTÜK', 'https://news.google.com', 'https://news.google.com/rss/search?q=RT%C3%9CK&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sayıştay', 'https://news.google.com', 'https://news.google.com/rss/search?q=Say%C4%B1%C5%9Ftay&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Danıştay', 'https://news.google.com', 'https://news.google.com/rss/search?q=Dan%C4%B1%C5%9Ftay&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Yargıtay', 'https://news.google.com', 'https://news.google.com/rss/search?q=Yarg%C4%B1tay&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Anayasa Mahkemesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Anayasa%20Mahkemesi%20AYM&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · YSK', 'https://news.google.com', 'https://news.google.com/rss/search?q=Y%C3%BCksek%20Se%C3%A7im%20Kurulu%20YSK&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · HSK', 'https://news.google.com', 'https://news.google.com/rss/search?q=Hakimler%20ve%20Savc%C4%B1lar%20Kurulu&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Diyanet', 'https://news.google.com', 'https://news.google.com/rss/search?q=Diyanet%20%C4%B0%C5%9Fleri%20Ba%C5%9Fkanl%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Boğaziçi Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Bo%C4%9Fazi%C3%A7i%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İTÜ', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0stanbul%20Teknik%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · ODTÜ', 'https://news.google.com', 'https://news.google.com/rss/search?q=ODT%C3%9C&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Hacettepe', 'https://news.google.com', 'https://news.google.com/rss/search?q=Hacettepe%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ankara Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ankara%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İstanbul Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C4%B0stanbul%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Ege Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ege%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Bilkent', 'https://news.google.com', 'https://news.google.com/rss/search?q=Bilkent%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Koç Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Ko%C3%A7%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sabancı Üniversitesi', 'https://news.google.com', 'https://news.google.com/rss/search?q=Sabanc%C4%B1%20%C3%9Cniversitesi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Kripto', 'https://news.google.com', 'https://news.google.com/rss/search?q=kripto%20para%20Bitcoin%20T%C3%BCrkiye&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tahvil', 'https://news.google.com', 'https://news.google.com/rss/search?q=devlet%20tahvili&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · CDS', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20risk%20primi%20CDS&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Rezervler', 'https://news.google.com', 'https://news.google.com/rss/search?q=Merkez%20Bankas%C4%B1%20rezervleri&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Turist sayısı', 'https://news.google.com', 'https://news.google.com/rss/search?q=turist%20say%C4%B1s%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Otomobil satışları', 'https://news.google.com', 'https://news.google.com/rss/search?q=otomobil%20sat%C4%B1%C5%9F%20rakamlar%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Konut satışları', 'https://news.google.com', 'https://news.google.com/rss/search?q=konut%20sat%C4%B1%C5%9F%20istatistik&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sanayi üretimi', 'https://news.google.com', 'https://news.google.com/rss/search?q=sanayi%20%C3%BCretim%20endeksi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · PMI', 'https://news.google.com', 'https://news.google.com/rss/search?q=imalat%20PMI&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Bütçe açığı', 'https://news.google.com', 'https://news.google.com/rss/search?q=b%C3%BCt%C3%A7e%20a%C3%A7%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Dış ticaret', 'https://news.google.com', 'https://news.google.com/rss/search?q=d%C4%B1%C5%9F%20ticaret%20a%C3%A7%C4%B1%C4%9F%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Tüketici güveni', 'https://news.google.com', 'https://news.google.com/rss/search?q=t%C3%BCketici%20g%C3%BCven%20endeksi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Asgari geçim', 'https://news.google.com', 'https://news.google.com/rss/search?q=asgari%20ge%C3%A7im%20a%C3%A7l%C4%B1k%20yoksulluk%20s%C4%B1n%C4%B1r%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Memur zammı', 'https://news.google.com', 'https://news.google.com/rss/search?q=memur%20maa%C5%9F%20zamm%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Öğretmen ataması', 'https://news.google.com', 'https://news.google.com/rss/search?q=%C3%B6%C4%9Fretmen%20atamas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sağlıkta şiddet', 'https://news.google.com', 'https://news.google.com/rss/search?q=sa%C4%9Fl%C4%B1kta%20%C5%9Fiddet&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Hava kirliliği', 'https://news.google.com', 'https://news.google.com/rss/search?q=hava%20kirlili%C4%9Fi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Su krizi', 'https://news.google.com', 'https://news.google.com/rss/search?q=baraj%20doluluk%20su%20krizi&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Asgari ücret zammı', 'https://news.google.com', 'https://news.google.com/rss/search?q=asgari%20%C3%BCcret%20zamm%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Sel', 'https://news.google.com', 'https://news.google.com/rss/search?q=sel%20bask%C4%B1n%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Maden kazası', 'https://news.google.com', 'https://news.google.com/rss/search?q=maden%20kazas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İş kazası', 'https://news.google.com', 'https://news.google.com/rss/search?q=i%C5%9F%20kazas%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Almanya', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Almanya&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Fransa', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Fransa&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · İngiltere', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20%C4%B0ngiltere&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Çin', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20%C3%87in&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Suudi Arabistan', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Suudi%20Arabistan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · BAE', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20BAE&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Katar', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Katar&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Pakistan', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Pakistan&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Türk dünyası', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrk%20Devletleri%20Te%C5%9Fkilat%C4%B1&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Balkanlar', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Balkanlar&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Afrika açılımı', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Afrika&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Orta Asya', 'https://news.google.com', 'https://news.google.com/rss/search?q=T%C3%BCrkiye%20Orta%20Asya&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Doğu Akdeniz', 'https://news.google.com', 'https://news.google.com/rss/search?q=Do%C4%9Fu%20Akdeniz%20gerilim&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR'),
  ('Google Haberler — TR · Karadeniz', 'https://news.google.com', 'https://news.google.com/rss/search?q=Karadeniz%20do%C4%9Falgaz&hl=tr&gl=TR&ceid=TR:tr', 'rss', 'notr', 'tr', 'TR')
ON CONFLICT (feed_url) DO NOTHING;
