-- =====================================================================
-- Seed: Ulusal (TR) + uluslararası kuruluşların DOĞRUDAN kategori RSS'leri.
-- OTOMATİK ÜRETİLDİ. Kaynak: sources.data.ts buildCuratedExtra
-- Idempotent: ON CONFLICT (feed_url) DO NOTHING.  Toplam: 85
-- =====================================================================

INSERT INTO sources (name, homepage, feed_url, kind, orientation, lang, country_iso2) VALUES
  ('Hürriyet — Gündem', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/gundem', 'rss', 'notr', 'tr', 'TR'),
  ('Hürriyet — Ekonomi', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/ekonomi', 'rss', 'notr', 'tr', 'TR'),
  ('Hürriyet — Dünya', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/dunya', 'rss', 'notr', 'tr', 'TR'),
  ('Hürriyet — Teknoloji', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/teknoloji', 'rss', 'notr', 'tr', 'TR'),
  ('Hürriyet — Sağlık', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/saglik', 'rss', 'notr', 'tr', 'TR'),
  ('Milliyet — Ekonomi', 'https://www.milliyet.com.tr', 'https://www.milliyet.com.tr/rss/rssNew/ekonomiRss.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Milliyet — Dünya', 'https://www.milliyet.com.tr', 'https://www.milliyet.com.tr/rss/rssNew/dunyaRss.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Milliyet — Siyaset', 'https://www.milliyet.com.tr', 'https://www.milliyet.com.tr/rss/rssNew/siyasetRss.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Milliyet — Son Dakika', 'https://www.milliyet.com.tr', 'https://www.milliyet.com.tr/rss/rssNew/sondakikaRss.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Milliyet — Teknoloji', 'https://www.milliyet.com.tr', 'https://www.milliyet.com.tr/rss/rssNew/teknolojiRss.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Sabah — Gündem', 'https://www.sabah.com.tr', 'https://www.sabah.com.tr/rss/gundem.xml', 'rss', 'iktidar', 'tr', 'TR'),
  ('Sabah — Ekonomi', 'https://www.sabah.com.tr', 'https://www.sabah.com.tr/rss/ekonomi.xml', 'rss', 'iktidar', 'tr', 'TR'),
  ('Sabah — Dünya', 'https://www.sabah.com.tr', 'https://www.sabah.com.tr/rss/dunya.xml', 'rss', 'iktidar', 'tr', 'TR'),
  ('Sabah — Teknoloji', 'https://www.sabah.com.tr', 'https://www.sabah.com.tr/rss/teknoloji.xml', 'rss', 'iktidar', 'tr', 'TR'),
  ('NTV — Ekonomi', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/ekonomi.rss', 'rss', 'notr', 'tr', 'TR'),
  ('NTV — Dünya', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/dunya.rss', 'rss', 'notr', 'tr', 'TR'),
  ('NTV — Teknoloji', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/teknoloji.rss', 'rss', 'notr', 'tr', 'TR'),
  ('NTV — Sağlık', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/saglik.rss', 'rss', 'notr', 'tr', 'TR'),
  ('NTV — Son Dakika', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/son-dakika.rss', 'rss', 'notr', 'tr', 'TR'),
  ('CNN Türk — Türkiye', 'https://www.cnnturk.com', 'https://www.cnnturk.com/feed/rss/turkiye/news', 'rss', 'notr', 'tr', 'TR'),
  ('CNN Türk — Ekonomi', 'https://www.cnnturk.com', 'https://www.cnnturk.com/feed/rss/ekonomi/news', 'rss', 'notr', 'tr', 'TR'),
  ('CNN Türk — Dünya', 'https://www.cnnturk.com', 'https://www.cnnturk.com/feed/rss/dunya/news', 'rss', 'notr', 'tr', 'TR'),
  ('CNN Türk — Teknoloji', 'https://www.cnnturk.com', 'https://www.cnnturk.com/feed/rss/teknoloji/news', 'rss', 'notr', 'tr', 'TR'),
  ('Habertürk — Gündem', 'https://www.haberturk.com', 'https://www.haberturk.com/rss/gundem.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Habertürk — Ekonomi', 'https://www.haberturk.com', 'https://www.haberturk.com/rss/ekonomi.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Habertürk — Dünya', 'https://www.haberturk.com', 'https://www.haberturk.com/rss/dunya.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Habertürk — Teknoloji', 'https://www.haberturk.com', 'https://www.haberturk.com/rss/teknoloji.xml', 'rss', 'notr', 'tr', 'TR'),
  ('Cumhuriyet — Türkiye', 'https://www.cumhuriyet.com.tr', 'https://www.cumhuriyet.com.tr/rss/turkiye.xml', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Cumhuriyet — Ekonomi', 'https://www.cumhuriyet.com.tr', 'https://www.cumhuriyet.com.tr/rss/ekonomi.xml', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Cumhuriyet — Dünya', 'https://www.cumhuriyet.com.tr', 'https://www.cumhuriyet.com.tr/rss/dunya.xml', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Cumhuriyet — Siyaset', 'https://www.cumhuriyet.com.tr', 'https://www.cumhuriyet.com.tr/rss/siyaset.xml', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Sözcü — Gündem', 'https://www.sozcu.com.tr', 'https://www.sozcu.com.tr/kategori/gundem/feed/', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Sözcü — Ekonomi', 'https://www.sozcu.com.tr', 'https://www.sozcu.com.tr/kategori/ekonomi/feed/', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Sözcü — Dünya', 'https://www.sozcu.com.tr', 'https://www.sozcu.com.tr/kategori/dunya/feed/', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Yeni Şafak — Gündem', 'https://www.yenisafak.com', 'https://www.yenisafak.com/rss?xml=gundem', 'rss', 'iktidar', 'tr', 'TR'),
  ('Yeni Şafak — Ekonomi', 'https://www.yenisafak.com', 'https://www.yenisafak.com/rss?xml=ekonomi', 'rss', 'iktidar', 'tr', 'TR'),
  ('Yeni Şafak — Dünya', 'https://www.yenisafak.com', 'https://www.yenisafak.com/rss?xml=dunya', 'rss', 'iktidar', 'tr', 'TR'),
  ('Yeni Şafak — Politika', 'https://www.yenisafak.com', 'https://www.yenisafak.com/rss?xml=politika', 'rss', 'iktidar', 'tr', 'TR'),
  ('AA — Politika', 'https://www.aa.com.tr', 'https://www.aa.com.tr/tr/rss/default?cat=politika', 'rss', 'iktidar', 'tr', 'TR'),
  ('AA — Spor', 'https://www.aa.com.tr', 'https://www.aa.com.tr/tr/rss/default?cat=spor', 'rss', 'iktidar', 'tr', 'TR'),
  ('AA — Analiz', 'https://www.aa.com.tr', 'https://www.aa.com.tr/tr/rss/default?cat=analiz', 'rss', 'iktidar', 'tr', 'TR'),
  ('AA — Bilim-Teknoloji', 'https://www.aa.com.tr', 'https://www.aa.com.tr/tr/rss/default?cat=bilim-teknoloji', 'rss', 'iktidar', 'tr', 'TR'),
  ('AA English — World', 'https://www.aa.com.tr/en', 'https://www.aa.com.tr/en/rss/default?cat=world', 'rss', 'iktidar', 'en', 'TR'),
  ('Dünya Gazetesi', 'https://www.dunya.com', 'https://www.dunya.com/rss', 'rss', 'notr', 'tr', 'TR'),
  ('BloombergHT', 'https://www.bloomberght.com', 'https://www.bloomberght.com/rss', 'rss', 'notr', 'tr', 'TR'),
  ('DHA', 'https://www.dha.com.tr', 'https://www.dha.com.tr/rss', 'rss', 'notr', 'tr', 'TR'),
  ('İHA', 'https://www.iha.com.tr', 'https://www.iha.com.tr/rss/', 'rss', 'notr', 'tr', 'TR'),
  ('OdaTV', 'https://www.odatv.com', 'https://www.odatv.com/rss.xml', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Gerçek Gündem', 'https://www.gercekgundem.com', 'https://www.gercekgundem.com/rss', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Yeniçağ', 'https://www.yenicaggazetesi.com.tr', 'https://www.yenicaggazetesi.com.tr/rss', 'rss', 'muhalefet', 'tr', 'TR'),
  ('Türkiye Gazetesi', 'https://www.turkiyegazetesi.com.tr', 'https://www.turkiyegazetesi.com.tr/rss', 'rss', 'iktidar', 'tr', 'TR'),
  ('Star', 'https://www.star.com.tr', 'https://www.star.com.tr/rss/rss.asp', 'rss', 'iktidar', 'tr', 'TR'),
  ('Sputnik Türkçe', 'https://anadolu.sputniknews.com.tr', 'https://anadolu.sputniknews.com.tr/export/rss2/archive/index.xml', 'rss', 'uluslararasi', 'tr', 'TR'),
  ('BBC — Middle East', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('BBC — Europe', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/world/europe/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('BBC — Asia', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/world/asia/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('BBC — US & Canada', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('BBC — Africa', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/world/africa/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('Guardian — Middle East', 'https://www.theguardian.com', 'https://www.theguardian.com/world/middleeast/rss', 'rss', 'uluslararasi', 'en', 'GB'),
  ('Guardian — Europe', 'https://www.theguardian.com', 'https://www.theguardian.com/world/europe-news/rss', 'rss', 'uluslararasi', 'en', 'GB'),
  ('Guardian — US', 'https://www.theguardian.com', 'https://www.theguardian.com/us-news/rss', 'rss', 'uluslararasi', 'en', 'US'),
  ('Guardian — Environment', 'https://www.theguardian.com', 'https://www.theguardian.com/environment/rss', 'rss', 'uluslararasi', 'en', 'GB'),
  ('Guardian — Science', 'https://www.theguardian.com', 'https://www.theguardian.com/science/rss', 'rss', 'uluslararasi', 'en', 'GB'),
  ('NYT — Middle East', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('NYT — Europe', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('NYT — Asia Pacific', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('NYT — Economy', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('NYT — Science', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml', 'rss', 'uluslararasi', 'en', 'US'),
  ('CNN — Europe', 'https://www.cnn.com', 'http://rss.cnn.com/rss/edition_europe.rss', 'rss', 'uluslararasi', 'en', 'US'),
  ('CNN — Middle East', 'https://www.cnn.com', 'http://rss.cnn.com/rss/edition_meast.rss', 'rss', 'uluslararasi', 'en', 'US'),
  ('CNN — Business', 'https://www.cnn.com', 'http://rss.cnn.com/rss/money_news_international.rss', 'rss', 'uluslararasi', 'en', 'US'),
  ('DW — Deutsch', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-de-all', 'rss', 'uluslararasi', 'de', 'DE'),
  ('The Economist — Finance', 'https://www.economist.com', 'https://www.economist.com/finance-and-economics/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('The Economist — Business', 'https://www.economist.com', 'https://www.economist.com/business/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('The Economist — Europe', 'https://www.economist.com', 'https://www.economist.com/europe/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('The Economist — MEA', 'https://www.economist.com', 'https://www.economist.com/middle-east-and-africa/rss.xml', 'rss', 'uluslararasi', 'en', 'GB'),
  ('Washington Post — Technology', 'https://www.washingtonpost.com', 'https://feeds.washingtonpost.com/rss/business/technology', 'rss', 'uluslararasi', 'en', 'US'),
  ('Middle East Eye', 'https://www.middleeasteye.net', 'https://www.middleeasteye.net/rss', 'rss', 'uluslararasi', 'en', NULL),
  ('Al-Monitor', 'https://www.al-monitor.com', 'https://www.al-monitor.com/rss', 'rss', 'uluslararasi', 'en', NULL),
  ('Rudaw — English', 'https://www.rudaw.net', 'https://www.rudaw.net/rss?language=english', 'rss', 'uluslararasi', 'en', 'IQ'),
  ('The New Arab', 'https://www.newarab.com', 'https://www.newarab.com/rss', 'rss', 'uluslararasi', 'en', NULL),
  ('Reuters — Business (Google)', 'https://www.reuters.com', 'https://news.google.com/rss/search?q=when:24h+site:reuters.com+business&hl=en-US&gl=US&ceid=US:en', 'rss', 'uluslararasi', 'en', NULL),
  ('CNBC — World', 'https://www.cnbc.com', 'https://www.cnbc.com/id/100727362/device/rss/rss.html', 'rss', 'uluslararasi', 'en', 'US'),
  ('CNBC — Economy', 'https://www.cnbc.com', 'https://www.cnbc.com/id/20910258/device/rss/rss.html', 'rss', 'uluslararasi', 'en', 'US'),
  ('MarketWatch — Top', 'https://www.marketwatch.com', 'https://feeds.marketwatch.com/marketwatch/topstories/', 'rss', 'uluslararasi', 'en', 'US')
ON CONFLICT (feed_url) DO NOTHING;
